#!/usr/bin/env groovy
library 'jenkins-lib'

pipeline {

  agent {
    kubernetes {
      cloud getKubernetesClusterName()
      yaml readK8sConfig('build', '2Gi', '1')
    }
  }

  options {
    timestamps()
    ansiColor('xterm')
  }

  environment {
    SCMVARS = null
    CREDENTIALS_ID='86f3b7e9-aec0-4914-bc4c-24bfa709fab8'
    CI=true
  }

  stages {
    stage ('Checkout') {
      steps {
        checkout scm
      }
    }

    stage ('Boostrap') {
      steps {
        sh 'yarn && yarn bootstrap'
      }
    }

    stage('Deploy') {
      steps {
        withCredentials([
          [
            $class: 'UsernamePasswordMultiBinding',
            credentialsId: 'artifactory-sirenpublisher',
            usernameVariable: 'ARTIFACTORY_USERNAME',
            passwordVariable: 'ARTIFACTORY_PASSWORD'
          ]
        ]) {
          sh 'curl -u"${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}" https://artifactory.siren.io/artifactory/api/npm/sirensolutions-npm-local/auth/antv > ~/.npmrc'
          script {
            ['core', 'element', 'plugin', 'pc', 'g6'].each {
              def packageJSON = readJSON file: "${env.WORKSPACE}/packages/${it}/package.json"
              def version = packageJSON.version
              def packageName = (it == 'g6' ? 'g6' : "g6-${it}")

              sh "curl -u\"\${ARTIFACTORY_USERNAME}:\${ARTIFACTORY_PASSWORD}\" -X DELETE https://artifactory.siren.io/ui/repos/tree/General/sirensolutions-npm-local/@antv/${packageName}/-/@antv/${packageName}-${version}.tgz || true"
              sh "curl -u\"\${ARTIFACTORY_USERNAME}:\${ARTIFACTORY_PASSWORD}\" -X DELETE https://artifactory.siren.io/ui/repos/tree/General/sirensolutions-npm-local/.npm/@antv/${packageName}/@antv/${packageName}-${version}.json || true"

              sh "cd packages/${it} && npm run build && npm publish --registry=https://artifactory.siren.io/artifactory/api/npm/sirensolutions-npm-local && cd .."
            }
          }
        }
      }
    }

  }

}
